# -*- coding: utf-8 -*-
"""hola mundo.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1by-wDiTQQy_pt-2Z0l8gm7FJZe8zE6Qm
"""

n1=float(input("Intro número uno: "))
n2=float(input("Intro numero dos: "))
suma=n1+n2

print("La suma es: ",suma)